Fix win32 regression introduced in 36e96bf
libnet_if_addr.c(467): error C2082: redefinition of formal parameter 'dev'

Signed-off-by: Joachim Wiberg <troglobit@gmail.com>